In [2]:
import os
from sqlalchemy import create_engine
from dotenv import load_dotenv 

load_dotenv()

# Database credentials
user = os.getenv('postgresql_username')
password = os.getenv('postgresql_password')
host = 'cm-de-k1-db.c9ms60q6cw37.ap-southeast-2.rds.amazonaws.com'
port = '5432'
database = 'postgres'

# Construct the connection string
# The 'postgresql+psycopg2' part specifies the dialect and driver
connection_string = f'postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}'

# Create the SQLAlchemy engine
engine = create_engine(connection_string)
connection = engine.connect()

Read data

In [3]:
import pandas as pd
# HINTS
# 1. Read data from SQL table coffee.sales
# 2. Read all data and export to 
schema = 'coffee'
table = 'sales'
df = pd.read_sql(sql='select * from coffee.sales',con=connection)
df

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
2688,2024-12-31,2024-12-31 17:10:17.537,card,ANON-0000-0000-0525,35.76,Latte
2689,2024-12-31,2024-12-31 17:30:52.785,card,ANON-0000-0000-1064,30.86,Americano with Milk
2690,2024-12-31,2024-12-31 17:31:48.543,card,ANON-0000-0000-1065,35.76,Cappuccino
2691,2024-12-31,2024-12-31 19:07:25.413,card,ANON-0000-0000-1066,35.76,Latte
2692,2024-12-31,2024-12-31 19:08:38.899,card,ANON-0000-0000-1066,35.76,Hot Chocolate

Load to storage

In [5]:
import sqlite3

# create destination database
dest_database_file = "destination.db"
dest_conn = sqlite3.connect(dest_database_file)

# 1. Upload data to a table named: coffee_sales
df.to_sql('coffee_sales',dest_conn,if_exists='replace',index=False)

2693

In [11]:
df_lite = pd.read_sql('SELECT * FROM coffee_sales ORDER BY datetime',con=dest_conn)
df_lite

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520000,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539000,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089000,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006000,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626000,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
2688,2024-12-31,2024-12-31 17:10:17.537000,card,ANON-0000-0000-0525,35.76,Latte
2689,2024-12-31,2024-12-31 17:30:52.785000,card,ANON-0000-0000-1064,30.86,Americano with Milk
2690,2024-12-31,2024-12-31 17:31:48.543000,card,ANON-0000-0000-1065,35.76,Cappuccino
2691,2024-12-31,2024-12-31 19:07:25.413000,card,ANON-0000-0000-1066,35.76,Latte
2692,2024-12-31,2024-12-31 19:08:38.899000,card,ANON-0000-0000-1066,35.76,Hot Chocolate

Incremental Loading

In [ ]:
# 1. Read latest data from storage
# 2. Filter incremental records from source
# 3. Load as 'append' to existing table